// Film folders and the registry: pure helpers shared by tools/new-film.mjs and its tests.
import {writeFileSync} from 'node:fs';
import path from 'node:path';
import {FILMS_DIR, listFilms} from './kit.mjs';

const RESERVED = new Set(
	'break case catch class const continue debugger default delete do else enum export extends false finally for function if import in instanceof new null return super switch this throw true try typeof var void while with yield let static implements interface package private protected public await'.split(' '),
);

// "my-film" -> "myFilm"; a leading digit or a reserved word gets a prefix so it is a valid name.
export const importAlias = (id) => {
	const camel = id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
	if (/^[0-9]/.test(camel)) return `f${camel}`;
	return RESERVED.has(camel) ? `${camel}Film` : camel;
};

// "my-film" -> "MyFilm": the name of the film's top-level component and its file.
export const componentName = (id, taken = []) => {
	let name = id
		.split('-')
		.map((p) => p.charAt(0).toUpperCase() + p.slice(1))
		.join('');
	if (/^[0-9]/.test(name)) name = `Film${name}`;
	// film.ts and Film.tsx clash on a case-insensitive disk, and so would theme.ts and Theme.tsx.
	if (taken.some((t) => t.toLowerCase() === name.toLowerCase())) name = `${name}Film`;
	return name;
};

export const titleFrom = (id) => {
	const words = id.split('-').join(' ');
	return words.charAt(0).toUpperCase() + words.slice(1);
};

export const registrySource = (ids) => {
	const lines = ['// Generated by tools/new-film.mjs from the folders in src/films. Do not edit by hand.'];
	for (const id of ids) lines.push(`import {film as ${importAlias(id)}} from './${id}/film';`);
	lines.push('', `export const FILMS = [${ids.map(importAlias).join(', ')}];`, '');
	return lines.join('\n');
};

export const writeRegistry = () => {
	const ids = listFilms();
	writeFileSync(path.join(FILMS_DIR, 'registry.ts'), registrySource(ids));
	return ids;
};

export const STUBS = {
	'brief.md': (title) => `# Brief: ${title}

Fill this in before anything else, in plain words. Every later choice is checked against it.

## Who it is for

## The one thing they must remember

## What they should feel

## Length, shape and where it plays

Seconds, aspect ratio, platform, sound on or off.

## Must include, must avoid
`,
	'treatment.md': (title) => `# Treatment: ${title}

The film in time, picture and sound side by side, before any code. One row per beat that matters.
The times here become the named moments in \`beatmap.ts\`.

| Time (s) | Picture | Sound | Why it is there |
|---|---|---|---|
|  |  |  |  |
`,
	'expected.md': (title) => `# Expected: ${title}

Write these down BEFORE the first render, then compare with what \`npm run release\` measures.
A prediction you did not write down cannot be wrong, so it cannot teach you anything.

## The audit

- Profile (dark, standard, light or ui-light):
- Mean luminance:
- Loudness range, and where the loudest moment is:
- Longest hold, and where:

## A first-time viewer

- What they can say the film is about after one viewing:
- The moment they will remember:
`,
};

// A single-quoted JavaScript string literal for a title such as "Who's singing".
export const jsString = (s) => {
	const backslash = String.fromCharCode(92);
	const body = String(s)
		.split(backslash)
		.join(backslash + backslash)
		.split("'")
		.join(backslash + "'")
		.replace(/[\r\n]+/g, ' ');
	return `'${body}'`;
};
