// Bundling and rendering through Remotion's Node APIs. Every film renders from its own generated
// entry point (out/.entry/<id>/index.tsx), so a half-written film in another folder can never stop
// this one rendering. Studio still shows every film through src/index.ts.
import {cpSync, existsSync, mkdirSync, rmSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {OUT_DIR, PUBLIC_DIR, ROOT, UsageError, filmDir} from './kit.mjs';
import {resolveGl} from './gl.mjs';

export const loadRemotion = async () => {
	try {
		const bundler = await import('@remotion/bundler');
		const renderer = await import('@remotion/renderer');
		return {bundle: bundler.bundle, renderer};
	} catch (err) {
		if (!existsSync(path.join(ROOT, 'node_modules', '@remotion', 'renderer'))) {
			throw new UsageError('The Remotion packages are not installed yet. Run: npm ci   (then npm run doctor)');
		}
		throw err;
	}
};

const posix = (p) => p.split(path.sep).join('/');

export const entryDir = (id) => path.join(OUT_DIR, '.entry', id);

// The generated entry and a tsconfig that typechecks exactly what it imports.
export const writeFilmEntry = (id) => {
	const dir = entryDir(id);
	mkdirSync(dir, {recursive: true});
	const filmModule = posix(path.relative(dir, path.join(filmDir(id), 'film')));
	const entry = path.join(dir, 'index.tsx');
	writeFileSync(
		entry,
		`// Generated by tools/lib/remotion.mjs before every render: one film per bundle. Do not edit.
import React from 'react';
import {Composition, registerRoot} from 'remotion';
import {film} from '${filmModule}';

const Root: React.FC = () => (
	<Composition id={film.id} component={film.component} durationInFrames={film.durationInFrames} fps={film.fps} width={film.width} height={film.height} />
);

registerRoot(Root);
`,
	);
	writeFileSync(
		path.join(dir, 'tsconfig.json'),
		JSON.stringify({extends: posix(path.relative(dir, path.join(ROOT, 'tsconfig.json'))), include: ['index.tsx']}, null, 2) + '\n',
	);
	return entry;
};

export const chromiumOptionsFor = (gl) => ({gl, ...(process.platform === 'linux' ? {enableMultiProcessOnLinux: true} : {})});

export const glFor = (flags = {}) => {
	if (typeof flags.gl === 'string') return {gl: flags.gl, source: '--gl'};
	return resolveGl(ROOT);
};

// The public folder a bundle carries: the shared fonts and test assets, plus (for a film) its own
// public/films/<id>/ and nothing of any other film's, copied fresh into `dest`. Bundling all of
// public/ copied every film's generated media into every render.
export const publicFor = (dest, {film = null} = {}) => {
	rmSync(dest, {recursive: true, force: true});
	mkdirSync(dest, {recursive: true});
	for (const sub of ['fonts', 'test', ...(film ? [path.join('films', film)] : [])]) {
		const from = path.join(PUBLIC_DIR, sub);
		if (existsSync(from)) cpSync(from, path.join(dest, sub), {recursive: true});
	}
	return dest;
};
export const filmPublic = (id) => publicFor(path.join(entryDir(id), 'public'), {film: id});

// Bundle once. Webpack's progress is noisy, so report every quarter. `publicDir` defaults to the
// shared assets only; pass filmPublic(id) for a film.
export const bundleEntry = async (bundle, entryPoint, {quiet = false, publicDir = null} = {}) => {
	let last = -1;
	const t0 = Date.now();
	const serveUrl = await bundle({
		entryPoint,
		rootDir: ROOT,
		publicDir: publicDir ?? publicFor(path.join(OUT_DIR, '.entry', '_shared', 'public')),
		onProgress: (p) => {
			const q = Math.floor(p / 25);
			if (!quiet && q > last && q < 4) {
				last = q;
				process.stdout.write(q === 0 ? 'bundling' : '.');
			}
		},
	});
	if (!quiet) process.stdout.write(` done in ${((Date.now() - t0) / 1000).toFixed(1)} s\n`);
	return serveUrl;
};

// Open one browser for a whole batch of stills or a render, with the chosen backend.
export const openKitBrowser = async (renderer, gl) =>
	renderer.openBrowser('chrome', {chromiumOptions: chromiumOptionsFor(gl), logLevel: 'error'});

export const selectFilm = async (renderer, {serveUrl, id, browser, gl}) => {
	try {
		return await renderer.selectComposition({serveUrl, id, puppeteerInstance: browser, chromiumOptions: chromiumOptionsFor(gl), logLevel: 'error'});
	} catch (err) {
		const msg = String(err?.message ?? err);
		if (/Could not find composition|No composition with the ID/i.test(msg)) {
			throw new UsageError(`The bundle has no composition "${id}". The id in src/films/${id}/film.ts must equal its folder name.`);
		}
		throw err;
	}
};

// The first line of a render error is usually the useful one; Remotion appends a long stack.
export const shortError = (err, lines = 4) =>
	String(err?.message ?? err)
		.split('\n')
		.filter((l) => l.trim())
		.slice(0, lines)
		.join('\n  ');
