// new-film in a throwaway copy of the kit: the copy gets its own ids, its own component, blank
// paper trail and a score, appears in the registry, and the result typechecks.
import assert from 'node:assert/strict';
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {test} from 'node:test';
import {registrySource} from '../lib/films.mjs';
import {KIT, node, tempKit} from './helpers.mjs';

test('the registry keeps one import per film and a FILMS array', () => {
	assert.equal(
		registrySource(['hark', 'spring-launch', 'template']),
		[
			'// Generated by tools/new-film.mjs from the folders in src/films. Do not edit by hand.',
			"import {film as hark} from './hark/film';",
			"import {film as springLaunch} from './spring-launch/film';",
			"import {film as template} from './template/film';",
			'',
			'export const FILMS = [hark, springLaunch, template];',
			'',
		].join('\n'),
	);
});

test('new-film copies the template into a film that typechecks and is registered', (t) => {
	const kit = tempKit(t, {withSrc: true, nodeModules: true});
	const run = (...args) => node([path.join(kit, 'tools', 'new-film.mjs'), ...args], {cwd: kit});
	const r = run('spring-launch', '--title', "Spring's launch");
	assert.equal(r.status, 0, r.stderr + r.stdout);
	const dir = path.join(kit, 'src', 'films', 'spring-launch');
	const read = (f) => readFileSync(path.join(dir, f), 'utf8');

	assert.ok(existsSync(path.join(dir, 'SpringLaunch.tsx')), 'the component file is named after the film');
	assert.ok(!existsSync(path.join(dir, 'Template.tsx')));
	assert.ok(!existsSync(path.join(dir, 'README.md')), "the template's README describes the template and stays behind");
	assert.match(read('film.ts'), /id: 'spring-launch'/);
	assert.match(read('film.ts'), /title: 'Spring\\'s launch'/);
	assert.match(read('film.ts'), /import \{SpringLaunch\} from '\.\/SpringLaunch'/);
	assert.match(read('SpringLaunch.tsx'), /staticFile\('films\/spring-launch\/score\.wav'\)/);
	assert.match(read('score.mjs'), /public\/films\/spring-launch\/score\.wav/);
	assert.doesNotMatch(read('score.mjs') + read('SpringLaunch.tsx') + read('film.ts'), /films\/template\//);
	assert.match(read('brief.md'), /^# Brief: Spring's launch/);
	assert.doesNotMatch(read('brief.md'), /One clock/);
	assert.ok(existsSync(path.join(kit, 'public', 'films', 'spring-launch', 'score.wav')), 'the new film was scored straight away');

	const registry = readFileSync(path.join(kit, 'src', 'films', 'registry.ts'), 'utf8');
	assert.match(registry, /import \{film as springLaunch\} from '\.\/spring-launch\/film';/);
	assert.match(registry, /export const FILMS = \[springLaunch, template\];/);

	// Typecheck the registry: it imports both films, so this covers the copy and the template.
	writeFileSync(path.join(kit, 'tsconfig.check.json'), JSON.stringify({extends: './tsconfig.json', include: [], files: ['src/films/registry.ts']}));
	const tsc = node([path.join(KIT, 'node_modules', 'typescript', 'bin', 'tsc'), '--noEmit', '-p', path.join(kit, 'tsconfig.check.json')], {cwd: kit});
	assert.equal(tsc.status, 0, `typecheck failed:\n${tsc.stdout}${tsc.stderr}`);

	// Refuses to overwrite, and refuses ids that are not folder names.
	const again = run('spring-launch');
	assert.equal(again.status, 2);
	assert.match(again.stderr, /already exists/);
	assert.equal(run('Bad_Id').status, 2);
	assert.equal(run('template').status, 2);
});
