// Generated by tools/new-film.mjs from the folders in src/films. Do not edit by hand.
import {film as hark} from './hark/film';
import {film as template} from './template/film';

export const FILMS = [hark, template];
